# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'coDrive' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for coDrive

  target 'coDrive-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RNScreens', :path => '../node_modules/react-native-screens'

    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

    pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  end

  target 'coDriveTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'coDrive-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for coDrive-tvOS



end
