# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'coDrive' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for coDrive

  target 'coDrive-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'coDriveTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'coDrive-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for coDrive-tvOS



end
